#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Mon Nov 24 10:45:34 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
import  wx.gizmos   as  gizmos
# end wxGlade


class SnapshotDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SnapshotDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.text_name = wx.TextCtrl(self, wx.ID_ANY, _("unamed"))
        self.button_add = wx.Button(self, wx.ID_ANY, _("&Add"))
        self.static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        self.list_history = gizmos.EditableListBox(self, wx.ID_ANY, style=wx.gizmos.EL_ALLOW_DELETE|wx.gizmos.EL_ALLOW_EDIT)
        self.button_load = wx.Button(self, wx.ID_ANY, _("&Load"))
        self.button_done = wx.Button(self, wx.ID_ANY, _("&Done"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnAdd, self.button_add)
        self.Bind(wx.EVT_BUTTON, self.OnLoad, self.button_load)
        self.Bind(wx.EVT_BUTTON, self.OnDone, self.button_done)
        # end wxGlade
        self.Bind(wx.EVT_CLOSE, self.OnClose)

    def __set_properties(self):
        # begin wxGlade: SnapshotDialog.__set_properties
        self.SetTitle(_("sptk lcd snapshot"))
        self.SetSize((464, 422))
        self.text_name.SetMinSize((-1, 40))
        self.text_name.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_name.SetFocus()
        self.button_add.SetMinSize((-1, 40))
        self.button_add.SetDefault()
        self.button_load.SetMinSize((-1, 70))
        self.button_done.SetMinSize((-1, 50))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SnapshotDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add((20, 20), 0, 0, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_4.Add(self.text_name, 1, 0, 0)
        sizer_4.Add((10, 20), 0, 0, 0)
        sizer_4.Add(self.button_add, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_3.Add((20, 10), 0, 0, 0)
        sizer_3.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_3.Add((20, 10), 0, 0, 0)
        sizer_5.Add(self.list_history, 1, wx.EXPAND, 0)
        sizer_5.Add((10, 20), 0, 0, 0)
        sizer_6.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_6.Add(self.button_load, 0, wx.ALIGN_BOTTOM, 0)
        sizer_6.Add((20, 10), 0, 0, 0)
        sizer_6.Add(self.button_done, 0, 0, 0)
        sizer_5.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add((20, 20), 0, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade
    
    def OnClose(self, event):
        wx.Exit()
        event.Skip()

    def OnAdd(self, event):  # wxGlade: SnapshotDialog.<event_handler>
        event.Skip()

    def OnLoad(self, event):  # wxGlade: SnapshotDialog.<event_handler>
        event.Skip()

    def OnDone(self, event):  # wxGlade: SnapshotDialog.<event_handler>
        wx.Exit()
        event.Skip()

# end of class SnapshotDialog
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_snapshot = SnapshotDialog(None, wx.ID_ANY, "")
    app.SetTopWindow(dialog_snapshot)
    dialog_snapshot.Show()
    app.MainLoop()
